/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
 /* docsSidebar: [
    'Introduction',
    'Community Incentives',
    {
      type: 'category',
      label: 'Mafia-Fi',
      link: {
        type: 'generated-index',
        title: 'Mafia-Fi',
        description:
          "Let's learn about the most important Mafia Finance",
        keywords: ['mafia-fi'],
        //image: '/img/docusaurus.png',
      },
      items: [
        'mafia-fi/Meme Mafia Swap',
        {
          type: 'category',
          label: 'Multi-Chain Accessibility',
          link: {
            type: 'doc',
            id: 'mafia-fi/docs/introduction',
          },
          items: [
            'guides/docs/create-doc',
            {
              type: 'category',
              label: 'Sidebar',
              link: {
                type: 'doc',
                id: 'guides/docs/sidebar/index',
              },
              items: [
                'guides/docs/sidebar/items',
                'guides/docs/sidebar/autogenerated',
                'guides/docs/sidebar/multiple-sidebars',
              ],
            },
            'guides/docs/versioning',
            'guides/docs/multi-instance',
          ],
        },
    {
      type: 'category',
      label: 'Mafia-Fi',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'Meme Mafia Swap',

      ],
    },
    
  ],
   */
};

export default sidebars;
